spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  jpa:
    spring.jpa.database-platfom: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
